### ISSUE TITLE
Get set up on semantic-release

### ISSUE THREAD

**Issue by wraithgar** [wraithgar/hapi-json-api#10]
greenkeeper apparently broke things?

This issue is now about switching to semantic-release

**Comment by gr2m** [comment]
did you get it working?

**Comment by wraithgar** [comment]
Yes I got it working, it was a combination of two things, first a misunderstanding on my part of exactly how greenkeeper works (it relies on existing CI tests to tell you if the build breaks).  Second, some hapi tweaks that changed in newer versions that exposed a duplicate `.connection` call I was making in the tests, and then also meant we don't have 100% coverage anymore cause newer hapi doesn't send `OPTIONS` requests to the plugin anymore.  It's all good now and today I guess I should finally knuckle down and learn travis myself or something (haven't done CI in any of my personal projects yet)

**Comment by gr2m** [comment]
I’m happy to help with any questions regarding greenkeeper.io. I can also very, very much recommend [semantic-release](https://github.com/semantic-release/semantic-release). It does the whole CI setup for you and releases new versions automatically based on a few commit conventions. Happy to help with that, too

**Comment by wraithgar** [comment]
Thanks, I looked into semantic-release and it looks nice. How does it work on pull requests?  I'd like to cut a major release since we bumped the `boom` version that gets returned from this module from 2 to 3.  Is that doable now that the commits are already in place or is this a "going forward" kind of module?

**Comment by wraithgar** [comment]
Trip report: will set this repo up once this issue is closed https://github.com/semantic-release/semantic-release/issues/114

**Comment by gr2m** [comment]
it’s a going forward kind of module. You can push an empty commit

```
git commit --allow-empty -m 'chore: major version bump

BREAKING CHANGE:

Bumped [boom](https://www.npmjs.com/package/boom) from to version 3. Changelog: <insert link here>
```

**Comment by gr2m** [comment]
Can you please try to change the package.json and see if that helps?

```diff
-  "repository": {
-    "type": "git",
-    "url": "git@github.com:wraithgar/hapi-json-api.git"
-  },
+  "repository": {
+    "type": "git",
+    "url": "https://github.com/wraithgar/hapi-json-api.git"
+  },
```

**Comment by wraithgar** [comment]
That worked, set it up, committed, semantic-release failed with:

```
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.
```

I think I didn't format my message right, will try again w/ an empty commit.

**Comment by wraithgar** [comment]
Looks like it worked, waiting for 2.0 to show up on npm now.

**Comment by wraithgar** [comment]
Yay 2.0 in the pipe, thanks

**Comment by gr2m** [comment]
Nice :+1: https://github.com/wraithgar/hapi-json-api/releases/tag/v2.0.0
