### ISSUE TITLE
workaround Firefox Bug sending charset=utf-8 media type parameter

### ISSUE THREAD

**Issue by gr2m** [wraithgar/hapi-json-api#11]
Hey @wraithgar, would you accept a PR to workaround Firefox’ bug described here?
https://github.com/json-api/json-api/issues/837

**Comment by gr2m** [comment]
hhmmm I’m trying to commit something for a PR, but I get a lint error:

```
$ gc test/ -m 'test: ignore charset=utf-8 media type parameter'
running lint...passed!
running validate...passed!
running test...failed!

/Users/gregor/Projects/hapi-json-api/node_modules/lab/lib/cli.js:5
const Fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
```

Any idea?

**Comment by gr2m** [comment]
I worked around it by temporarily remove `"test"` in `package.json`’s `"pre-commit"`

**Comment by wraithgar** [comment]
Not sure why tests aren't working locally for you, they are for travis-ci at least.   Typically this happens when you've switched to a pre-es6 version of node or something.
